### ISSUE TITLE
버그는 모르겠고

### ISSUE THREAD

**Issue by ddtt786** [EntLibrary/EntLib#1]
어떻게 불러오는지라도 일반인이 알아듣기 쉽게 해주시면 안되나요

**Comment by muno9748** [comment]
EntLib 3.0을 $.get으로 받아온 다음에 개발자가 코드를 짜고
그 개발자의 레포 파일을 import/$.get으로 불러오면 됩니다
이건 그냥 라이브러리일 뿐이지 개발은 전과 다름 없습니다
