### ISSUE TITLE
작품 만들기 화면에서 블록이 안 생겨남

### ISSUE THREAD

**Issue by ddtt786GH** [EntLibrary/EntLib#3]
**버그제보**
얫나래는 만들고 저장한 다음에도 다시 들어가서 코드 입력하면 블록 다시 생겻는데 지금은 안셍겨오

**버그가 재현될려면**
블록 만들고 코드 짠다음에 저장하고 다시 저장한 작품 만들기 화면에 드러가면 대빈다

**스크린샷**
![image](https://user-images.githubusercontent.com/77824221/122023635-b3661400-ce02-11eb-9c23-62dddf2fecd4.png)
![image](https://user-images.githubusercontent.com/77824221/122023647-b5c86e00-ce02-11eb-867f-6181956027cf.png)

**환경**
 - 브라우저 chrome
 - 버전 91

**추가설명**
추가설명이 있으면 적어주세요.

**Comment by muno9748** [comment]
[Issue #3](https://github.com/EntLibrary/EntLib/issues/3) Fixed on release [3.2.0](https://github.com/EntLibrary/EntLib/releases/tag/3.2.0)

This bug was caused because because the Entry's Server-API changed to GraphQL.
Thanks for support this project.
